export type Variety = {
  size: string;
  price: number;
};

export interface ProductType {
  _id: string,
  name: { en: string; ar: string };
  slug: string;
  type: "menu" | "occasion-cakes";
  category: { en: string; ar: string };
  description: { en: string; ar: string };
  ingredients: string[],
  image: string[];
  varieties: Variety[];           // unified sizes + prices
  flavors?: string[];             // optional
  tiers?: string[];               // optional
  messagePrice?: number;          // optional for personalized messages
  specialInstructions?: boolean;  // optional
}

export interface ReviewType {
  _id: string
  name: {
    en: string,
    ar: string
  }
  message: {
    en: string,
    ar: string
  }
  createdAt: string
  updatedAt: string
}

export interface CartItem {
  id: string;
  type: string; 
  titleEn: string;
  titleAr: string;
  image: string;
  flavor?: string;
  size: string;
  price: number; // dynamic for box
  quantity: number;
  messageOn: string
  message?: string
  specialInstruction?: string
  cupcakeImage?: string
  cartKey?: string
}

export type OrderStatus = 
  | "PENDING" 
  | "CONFIRMED" 
  | "DESIGN_APPROVED" 
  | "PREPARING" 
  | "READY" 
  | "OUT_FOR_DELIVERY" 
  | "DELIVERED" 
  | "CANCELLED";

export interface TierConfig {
  size: number;
  flavor: string;
  type: "Real" | "Dummy";
}

export interface CustomizeOrderType {
  _id: string;
  orderId: string;

  customer: {
    fullName: string;
    phone: string;
    email: string;
    city: string;
    address?: string; // Added address for delivery
  };

  cakeDetails: {
    occasion: string; // "wedding", "birthday", etc.
    numTiers: number;
    tiers: TierConfig[]; // The array of tiers
    messageOn: string;   // "no", "cake", or "board"
    cream: string
    message?: string;
    specialInstruction?: string;
    estimatedWeight: string;
    referenceImage?: string[];
  };

  delivery: {
    orderType: "pickup" | "delivery";
    deliveryDate: string;
    deliveryTime: string;
  };

  pricing: {
    totalPrice: number;     // Sum of cake tiers
    deliveryCharges: number;
    totalAmount: number;    // Final total
  };

  payment: {
    paymentProofImage: string
  }

  orderStatus: OrderStatus;

  createdAt: string;
  updatedAt: string;
}

export type OrderType = "MENU" | "OCCASION-CAKES";

export interface IOrderItem {
  _id?: string;
  productId: string; // MongoDB ObjectId as string
  name: string;
  size: string;
  flavor: string;
  quantity: number;
  messageOn: string;
  message: string;
  specialInstructions: string;
  orderType: OrderType;
  cupcakeReferenceImage: string
}

export interface MenuOccasionOrderType {
  _id: string;
  orderId: string; // The UUID generated by your schema
  customer: {
    fullName: string;
    phone: string;
    email: string;
    address: string;
    city: string;
    
  };
  items: IOrderItem[];
  pricing: {
    subtotal: number;
    deliveryCharges: number;
    total: number;
  };
  notes: string;
  delivery: {
    deliveryTimeSlot: string;
    deliveryDateSlot: string;
    deliveryType: "DELIVERY" | "PICKUP";
  };
  payment: {
    method: "ONLINE";
    paymentStatus: "PENDING" | "PAID" | "FAILED";
    paymentProofImage?: string; // Cloudinary URL
  };
  orderStatus: 
    | "PENDING" 
    | "CONFIRMED" 
    | "PREPARING" 
    | "READY" 
    | "OUT_FOR_DELIVERY" 
    | "DELIVERED" 
    | "CANCELLED";
  createdAt: string; // ISO Date string from timestamps: true
  updatedAt: string;
}
