export type Variety = {
  size: string;   // e.g., "6inch", "box6", "box12", "box"
  price: number;
};

export interface ProductType {
  _id: string,
  name: { en: string; ar: string };
  slug: string;
  type: "menu" | "occasion-cakes";
  category: { en: string; ar: string };
  description: { en: string; ar: string };
  image: string[];
  varieties: Variety[];           // unified sizes + prices
  flavors?: string[];             // optional
  tiers?: string[];               // optional
  messagePrice?: number;          // optional for personalized messages
  specialInstructions?: boolean;  // optional
}

export interface ReviewType {
  _id: string
  name: {
    en: string,
    ar: string
  }
  message: {
    en: string,
    ar: string
  }
  createdAt: string
  updatedAt: string
}

export interface CartItem {
  id: string;
  type: string; 
  titleEn: string;
  titleAr: string;
  image: string;
  flavor?: string;
  size: string;
  price: number; // dynamic for box
  quantity: number;
  messageOn: string
  message?: string
  specialInstruction?: string
  cartKey?: string
}

export type OrderStatus =
  | "PENDING"
  | "CONFIRMED"
  | "DESIGN_APPROVED"
  | "PREPARING"
  | "READY"
  | "OUT_FOR_DELIVERY"
  | "DELIVERED"
  | "CANCELLED";


export interface CustomizeOrderType {
  _id: string;
  orderId: string;

  customer: {
    fullName: string;
    phone: string;
    email: string;
    city: string;
  };

  cakeDetails?: {
    cakeFlavor?: string;
    cakeSize?: string;
    tierCakeSize?: string;
    cakeFlavorTopTier?: string;
    cakeFlavorBottomTier?: string;
    messageOn?: string;
    message?: string;
    specialInstruction?: string;
    referenceImage?: string[];
  };

  delivery: {
    deliveryDate: string;
    deliveryTime?: string;
  };

  pricing?: {
    totalPrice?: number;
    deliveryCharges?: number;
    totalAmount?: number;
  };

  orderStatus: OrderStatus;

  createdAt: string;
  updatedAt: string;
}

export type OrderType = "MENU" | "OCCASION-CAKES";

export interface IOrderItem {
  _id?: string;
  productId: string; // MongoDB ObjectId as string
  name: string;
  size: string;
  flavor: string;
  quantity: number;
  messageOn: string;
  message: string;
  specialInstructions: string;
  orderType: OrderType;
}

export interface MenuOccasionOrderType {
  _id: string;
  orderId: string; // The UUID generated by your schema
  customer: {
    fullName: string;
    phone: string;
    email: string;
    address: string;
    city: string;
  };
  items: IOrderItem[];
  pricing: {
    subtotal: number;
    deliveryCharges: number;
    total: number;
  };
  notes: string;
  delivery: {
    deliveryDate: string | Date;
    deliveryTimeSlot: string;
    deliveryType: "DELIVERY" | "PICKUP";
  };
  payment: {
    method: "ONLINE";
    paymentStatus: "PENDING" | "PAID" | "FAILED";
    paymentProofImage?: string; // Cloudinary URL
  };
  orderStatus: 
    | "PENDING" 
    | "CONFIRMED" 
    | "PREPARING" 
    | "READY" 
    | "OUT_FOR_DELIVERY" 
    | "DELIVERED" 
    | "CANCELLED";
  createdAt: string; // ISO Date string from timestamps: true
  updatedAt: string;
}
