import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";
import HtmlLangSetter from "@/components/customer/HTMLLangSelector";
import { roboto } from "@/lib/fonts";
import { CartContextProvider } from "@/context/CartContext";

export const metadata: Metadata = {
  title: "Amas Bakery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`antialiased ${roboto.className}`}
      >
        <LanguageProvider>
          <CartContextProvider>
            {children}
          </CartContextProvider>
        <HtmlLangSetter />
        </LanguageProvider>
      </body>
    </html>
  );
}
